### ISSUE TITLE
Parse and process manifest examples validation files

### ISSUE THREAD

**Issue by labra** [weso/rdfshape-client#118]
There was a feature that appeared in the first versions of RDFShape but was missed in the latest ones, which was to process manifest files with examples. 

This feature is available in ShEx simple and it works as follows:

When the client is passed a `manifestUrl=url` parameter, it parses the url which should be a manifest file like this one:

```yaml
---
- schemaLabel: Figures
  schemaURL: figures.shex
  dataLabel: r1 as figure
  dataURL: figures.ttl
  queryMap: |
    <http://example.org/r1>@<http://example.org/ColouredCircle>
  status: conformant
- schemaLabel: Example_x
  schemaURL: example_x.shex
  dataLabel: m24 as x_1
  dataURL: example_x.ttl
  queryMap: |
    <http://example.org/m24>@<http://example.org/X_1>
  status: conformant
- schemaLabel: Example_x
  schemaURL: example_x.shex
  dataLabel: m246 as x_2
  dataURL: example_x.ttl
  queryMap: |
    <http://example.org/m246>@<http://example.org/X_2>
  status: nonconformant
```

and it presents those options to the user. You can see it working [here](https://shex.io/webapps/shex.js/packages/shex-webapp/doc/shex-simple?manifestURL=https://raw.githubusercontent.com/weso/shex_extends_paper_companion/master/motivating_example/manifest.yml)
